# .streamlit/secrets.toml

[SUPABASE]
# Your Supabase Project URL
URL = "https://hirlhfvjwklfexuygeyp.supabase.co" 
# Your Supabase Anon Key
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcmxoZnZqd2tsZmV4dXlnZXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MDkyNjEsImV4cHAiOjIwNzk5ODUyNjF9.Gl_oHAgYOkNX4Xd2BOLBE8hCeyqaIondNbDYnfRGCqw"

# This is the name of the Storage Bucket you must create in your Supabase project
BUCKET = "recipes"